# Generated by Django 4.1 on 2022-09-10 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('links', '0006_alter_link_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IPアドレス')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='links.link', verbose_name='リンク')),
            ],
        ),
    ]
