# Generated by Django 4.1 on 2022-08-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='ip_address',
            field=models.GenericIPAddressField(auto_created=True, default=0),
            preserve_default=False,
        ),
    ]
