# Generated by Django 4.1 on 2022-08-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_alter_link_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='IPアドレス'),
        ),
    ]
