# Generated by Django 4.1 on 2022-09-10 12:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_alter_link_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.CharField(max_length=500, validators=[django.core.validators.URLValidator(schemes=('http', 'https'))], verbose_name='リンク'),
        ),
    ]
