# Generated by Django 4.1 on 2022-09-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0006_alter_link_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='like_count',
            field=models.IntegerField(default=0, verbose_name='いいね数'),
            preserve_default=False,
        ),
    ]
