# Generated by Django 4.1 on 2022-09-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0007_link_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='like_count',
            field=models.IntegerField(default=0, verbose_name='いいね数'),
        ),
    ]
